---
- name: istalling openstack
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - centos-release-openstack-ocata
    - https://rdoproject.org/repos/rdo-release.rpm
- name: yum update
  yum:
    update_cache: yes
    name: "{{ item }}"
  with_items:
    - python-openstackclient
    - openstack-selinux
#    state: installed
#    update_cache: yes
