---
- name: install rabbitmq
  yum:
    name: rabbitmq-server
    state: installed
    update_cache: yes
  notify: rabbitmq service
- name: adding rabbitmq user
  rabbitmq_user:
    user: openstack
    password: centos
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
